export const ADMIN_NAV_ITEMS = (
  pathname: string,
  locale: string,
  t: (key: string) => string,
) => [
  {
    id: 1,
    label: t("admin.sidebar.dashboard"),
    icon: "/images/admin/sidebar/user.svg",
    href: `/admin`,
    active: pathname === `/${locale}/admin`,
  },
  {
    id: 2,
    label: t("admin.sidebar.users"),
    icon: "/images/admin/sidebar/triangle-li.svg",
    href: `/admin/users`,
    active: pathname === `/${locale}/admin/users`,
  },
  {
    id: 3,
    label: t("admin.sidebar.requests"),
    icon: "/images/admin/sidebar/triangle-li.svg",
    href: `/admin/requests`,
    active: pathname === `/${locale}/admin/requests`,
  },
  {
    id: 4,
    label: t("admin.sidebar.propertyTypes"),
    icon: "/images/admin/sidebar/triangle-li.svg",
    href: `/admin/property-types`,
    active: pathname === `/${locale}/admin/property-types`,
  },
  {
    id: 5,
    label: t("admin.sidebar.properties"),
    icon: "/images/admin/sidebar/triangle-li.svg",
    href: `/admin/properties`,
    active: pathname === `/${locale}/admin/properties`,
  },
  {
    id: 6,
    label: t("admin.sidebar.locations"),
    icon: "/images/admin/sidebar/triangle-li.svg",
    href: `/admin/location-info`,
    active: pathname === `/${locale}/admin/location-info`,
  },
  {
    id: 7,
    label: t("admin.sidebar.newsTypes"),
    icon: "/images/admin/sidebar/triangle-li.svg",
    href: `/admin/news-types`,
    active: pathname === `/${locale}/admin/news-types`,
  },
  {
    id: 8,
    label: t("admin.sidebar.news"),
    icon: "/images/admin/sidebar/triangle-li.svg",
    href: `/admin/news`,
    active: pathname === `/${locale}/admin/news`,
  },
  {
    id: 9,
    label: t("admin.sidebar.banks"),
    icon: "/images/admin/sidebar/triangle-li.svg",
    href: `/admin/banks`,
    active: pathname === `/${locale}/admin/banks`,
  },
  {
    id: 10,
    label: t("admin.sidebar.settings"),
    icon: "/images/admin/sidebar/triangle-li.svg",
    href: `/admin/settings`,
    active: pathname === `/${locale}/admin/settings`,
  },
];
